version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: employee_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employee_database
      MYSQL_USER: developer
      MYSQL_PASSWORD: developer_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - employee_network
    command: --default-authentication-plugin=mysql_native_password

  employee-api:
    build: .
    container_name: employee_api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/employee_database?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: developer
      SPRING_DATASOURCE_PASSWORD: developer_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
    depends_on:
      - mysql
    networks:
      - employee_network
    volumes:
      - ./logs:/app/logs

volumes:
  mysql_data:
    driver: local

networks:
  employee_network:
    driver: bridge
